config/routes.rb
Rails.application.routes.draw do
  resources :previews, :except => [:edit]
  root 'previews#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/preview.rb
class Preview < ApplicationRecord
  validates :url, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  before_action :set_preview, only: [:show, :edit, :update, :destroy]
  include PreviewsHelper

  # GET /previews
  # GET /previews.json
  def index
    @previews = Preview.all
  end

  # GET /previews/1
  # GET /previews/1.json
  def show
  end

  # GET /previews/new
  def new
    @preview = Preview.new
  end

  # POST /previews
  # POST /previews.json
  def create

    @preview = Preview.where(url: preview_params[:url]).take

    @preview = Preview.new(preview_params) if @preview.nil?

    if @preview.title.blank? || @preview.image.blank?
      metatags = getMetaTags(@preview.url)

      if !metatags.nil?
        @preview.ogtype = metatags[:ogtype]
        @preview.title = metatags[:title]
        @preview.image = metatags[:image]
        @preview.description = metatags[:description]
      end
    end

    respond_to do |format|
      if @preview.save
        format.html { render @preview, status: :created }
        format.json { render :show, status: :created, location: @preview }
      else
        format.html { render :new }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previews/1
  # PATCH/PUT /previews/1.json
  def update
    respond_to do |format|
      if @preview.update(preview_params)
        format.html { redirect_to @preview, notice: 'Preview was successfully updated.' }
        format.json { render :show, status: :ok, location: @preview }
      else
        format.html { render :edit }
        format.json { render json: @preview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previews/1
  # DELETE /previews/1.json
  def destroy
    @preview.destroy
    respond_to do |format|
      format.html { redirect_to previews_url, notice: 'Preview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preview
      @preview = Preview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def preview_params
      params.require(:preview).permit(:url, :ogtype, :image, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/previews_helper.rb
require 'nokogiri'
require 'open-uri'

module PreviewsHelper
  def getMetaTags(url)
    return nil if url.blank?
    document = getDocument(url)
    return nil if document.nil?

    extractData(document)
  end

  private

  def extractData(document)
    result = Hash.new
    result[:title] = document.at('meta[property="og:title"]')['content'] if document.at('meta[property="og:title"]')
    result[:ogtype] = document.at('meta[property="og:type"]')['content'] if document.at('meta[property="og:type"]')
    result[:url] = document.at('meta[property="og:url"]')['content'] if document.at('meta[property="og:url"]')
    result[:image] = document.at('meta[property="og:image"]')['content'] if document.at('meta[property="og:image"]')
    result[:description] = document.at('meta[property="og:description"]')['content'] if document.at('meta[property="og:description"]')

    result
  end

  def getDocument(url)
    document = Nokogiri::HTML(URI.open(url).read)
    document.encoding = 'UTF-8'
    document
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpengraphPreviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/previews/_form.html.erb
<%= form_with(model: preview, id: 'new_preview') do |form| %>
  <% if preview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preview.errors.count, "error") %> prohibited this preview from being saved:</h2>

      <ul>
        <% preview.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, :class => 'form-control', :required => true %>
  </div>


  <div class="actions">
    <%= form.submit "Preview", data: { "disable-with": "Loading..." }, :class => 'btn btn-success' %>
  </div>

<% end %>

<br/>
<div id="result"></div>
<br/>

app/views/previews/_preview.html.erb
<div class="card" >
  <a href="<%= @preview.url %>">
    <img src="<%= @preview.image %>" class="card-img-top" alt="<%= @preview.title %>">
    <div class="card-body">
      <p class="card-text"><%= URI.parse(@preview.url).host %></p>
      <h5 class="card-title"><%= @preview.title %></h5>
      <p class="card-text"><%= @preview.description %></p>
    </div>
  </a>
</div>

app/views/previews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Previews</h1>

<%= link_to 'New Preview', new_preview_path, :class => 'btn btn-primary' %>

<br/>
<br/>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @previews.each do |preview| %>
      <tr>
        <td><%= preview.url %></td>
        <td><%= link_to 'Show', preview, :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', preview, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

app/views/previews/new.html.erb
<h1>New Preview</h1>

<%= render 'form', preview: @preview %>

<%= link_to 'Back', previews_path, :class => 'btn btn-primary' %>

app/views/previews/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'preview', preview: @preview %>

<br/>
<%= link_to 'Back', previews_path, :class => 'btn btn-primary' %>